<?php
return [
    'blueCards'=>[
        [//49
            'name'=>'軍閥',
            'image'=>'images/cards/blue/49.png',
            
            'function'=>'increasePoint',
            //gainDice=>,increasePoint
            'point'=>2,
            'functionTarget'=>'green',
            'costMoney'=>2,
            'gainMilitaryWhenBuy'=>3,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//50
            'name'=>'石匠',
            'image'=>'images/cards/blue/50.png',
            
            'function'=>'increasePoint',
            //gainDice=>,increasePoint
            'point'=>2,
            'functionTarget'=>'yellow',
            'costMoney'=>4,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//51
            'name'=>'貴婦',
            'image'=>'images/cards/blue/51.png',
            
            'function'=>'increasePoint',
            //gainDice=>,increasePoint
            'point'=>2,
            'functionTarget'=>'blue',
            'costMoney'=>4,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//52
            'name'=>'騎士',
            'image'=>'images/cards/blue/52.png',
            
            'function'=>'increasePoint',
            //gainDice=>,increasePoint
            'point'=>2,
            'functionTarget'=>'purple',
            'costMoney'=>2,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>1,
        ],
        [//53
            'name'=>'農夫',
            'image'=>'images/cards/blue/53.png',
            
            'function'=>'increasePoint',
            //gainDice=>,increasePoint
            'point'=>2,
            'functionTarget'=>'harvest',
            'costMoney'=>3,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//54
            'name'=>'工匠',
            'image'=>'images/cards/blue/54.png',
            
            'function'=>'increasePoint',
            //gainDice=>,increasePoint
            'point'=>2,
            'functionTarget'=>'production',
            'costMoney'=>3,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//55
            'name'=>'牧師',
            'image'=>'images/cards/blue/55.png',
            'function'=>'bad',
            //gainDice=>,increasePoint
            'point'=>0,
            'costMoney'=>2,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>4,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//56
            'name'=>'修女',
            'image'=>'images/cards/blue/56.png',
            
            'function'=>'gainDice',
            //gainDice=>,increasePoint
            'point'=>4,
            'functionTarget'=>'all',
            'costMoney'=>3,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//57
            'name'=>'統帥',
            'image'=>'images/cards/blue/57.png',
            
            'function'=>'gainDice',
            //gainDice=>,increasePoint
            'point'=>6,
            'functionTarget'=>'green',
            'costMoney'=>4,
            'gainMilitaryWhenBuy'=>2,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//58
            'name'=>'建築師',
            'image'=>'images/cards/blue/58.png',
            
            'function'=>'gainDice',
            //gainDice=>,increasePoint
            'point'=>6,
            'functionTarget'=>'yellow',
            'costMoney'=>4,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//59
            'name'=>'贊助人',
            'image'=>'images/cards/blue/59.png',
            
            'function'=>'gainDice',
            //gainDice=>,increasePoint
            'point'=>6,
            'functionTarget'=>'blue',
            'costMoney'=>3,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//60
            'name'=>'英雄',
            'image'=>'images/cards/blue/60.png',
            
            'function'=>'gainDice',
            //gainDice=>,increasePoint
            'point'=>6,
            'functionTarget'=>'purple',
            'costMoney'=>4,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>1,
        ],
        [//61
            'name'=>'農民',
            'image'=>'images/cards/blue/61.png',
            
            'function'=>'increasePoint',
            //gainDice=>,increasePoint
            'point'=>3,
            'functionTarget'=>'harvest',
            'costMoney'=>4,
            'gainMilitaryWhenBuy'=>3,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//62
            'name'=>'學者',
            'image'=>'images/cards/blue/62.png',
            
            'function'=>'increasePoint',
            //gainDice=>,increasePoint
            'point'=>3,
            'functionTarget'=>'production',
            'costMoney'=>4,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//63
            'name'=>'教皇信使',
            'image'=>'images/cards/blue/63.png',
            'function'=>null,
            //gainDice=>,increasePoint
            'point'=>0,
            'costMoney'=>5,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>3,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//64
            'name'=>'皇家信使',
            'image'=>'images/cards/blue/64.png',
            'function'=>null,
            //gainDice=>,increasePoint
            'point'=>0,
            'costMoney'=>5,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>3,
        ],
        [//65
            'name'=>'貴族',
            'image'=>'images/cards/blue/65.png',
            
            'function'=>'gainScore',
            //gainDice=>,increasePoint
            'point'=>0,
            'functionTarget'=>'green',
            'costMoney'=>6,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>2,
            'gainReelWhenBuy'=>0,
        ],
        [//66
            'name'=>'總督',
            'image'=>'images/cards/blue/66.png',
            
            'function'=>'gainScore',
            //gainDice=>,increasePoint
            'point'=>0,
            'functionTarget'=>'yellow',
            'costMoney'=>6,
            'gainMilitaryWhenBuy'=>3,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>2,
            'gainReelWhenBuy'=>0,
        ],
        [//67
            'name'=>'情婦',
            'image'=>'images/cards/blue/67.png',
            
            'function'=>'gainScore',
            //gainDice=>,increasePoint
            'point'=>2,
            'functionTarget'=>'blue',
            'costMoney'=>7,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>2,
            'gainReelWhenBuy'=>0,
        ],
        [//68
            'name'=>'傳令官',
            'image'=>'images/cards/blue/68.png',
            
            'function'=>'gainScore',
            //gainDice=>,increasePoint
            'point'=>0,
            'functionTarget'=>'purple',
            'costMoney'=>6,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>2,
            'gainReelWhenBuy'=>0,
        ],
        [//69
            'name'=>'紅衣主教',
            'image'=>'images/cards/blue/69.png',
            
            'function'=>'harvest',
            //gainDice=>,increasePoint
            'point'=>4,
            'costMoney'=>4,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>2,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//70
            'name'=>'主教',
            'image'=>'images/cards/blue/70.png',
            
            'function'=>'production',
            //gainDice=>,increasePoint
            'point'=>4,
            'costMoney'=>5,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>1,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>0,
        ],
        [//71
            'name'=>'將軍',
            'image'=>'images/cards/blue/71.png',
            
            'function'=>'gainScore',
            //gainDice=>,increasePoint
            'point'=>0,
            'functionTarget'=>'military',
            'costMoney'=>5,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>1,
            'gainReelWhenBuy'=>0,
        ],
        [//72
            'name'=>'大使',
            'image'=>'images/cards/blue/72.png',
            
            'function'=>'gainDice',
            //gainDice=>,increasePoint
            'point'=>7,
            'functionTarget'=>'all',
            'costMoney'=>6,
            'gainMilitaryWhenBuy'=>0,
            'gainBeliefWhenBuy'=>0,
            'gainScoreWhenBuy'=>0,
            'gainReelWhenBuy'=>1,
        ],
    ]
];